---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw6-askeeler-test-redis-deployment
  labels:
    app: hw-6askeeler-test-redis
    env: test
    username: askeeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw6-askeeler-test-redis
  template:
    metadata:
      labels:
        app: hw6-askeeler-test-redis
        env: test
        username: askeeler
    spec:
      containers:
        - name: redis-database
          image: redis:6
          ports:
          - name: http
            containerPort: 6379
          volumeMounts:
            - name: redis-test-volume
              mountPath: "/data"
      volumes:
        - name: redis-test-volume
          persistentVolumeClaim:
            claimName: redis-test-volume