---
apiVersion: v1
kind: Service
metadata:
  name: redis-test-service
  labels:
    app: redis-test-service
    env: test
    username: askeeler
spec:
  type: ClusterIP
  selector:
    app: hw6-askeeler-test-redis
    name: database
    env: test
    username: askeeler
  ports:
  - name: askeeler-test-redis
    port: 6427
    targetPort: 6413